### ISSUE TITLE
JSX parser macro [naive implementation]

### ISSUE THREAD

**Issue by norman784** [ahecha-co/ahecha#1]
Find a way to build a JSX parser macro, the main issue right now are the custom elements, I didn't find a way to build a node tree that also has custom elements.

The main issue is that you need to use generics, [Yew](https://github.com/yewstack/yew/blob/98821c4018b524e439bdf9b05e2f8372e37ef1bd/packages/yew/src/html/component/scope.rs#L30) seems to manage it with some kind of black magic ([Any](https://doc.rust-lang.org/std/any/trait.Any.html) and [TypeID](https://doc.rust-lang.org/std/any/struct.TypeId.html)), but I don't quite understand it yet.

## Why not use Yew?

1. Yew uses his own virtual dom.
2. AFAIK Yew doesn't support SSR.

## Are there other alternatives?

Yes.

1. [Sauron](https://github.com/ivanceras/sauron): Doesn't support JSX syntax, just plain html.
2. [Seed](https://github.com/seed-rs/seed): Doesn't use JSX syntax, uses a dsl like syntax that resembles to Elm.

## Worth mention:

- [Render.rs](https://github.com/render-rs/render.rs): used as base to build a jsx parser prototype.

## Goals

- Render static html.
- Render server side custom elements.
- Hydrate client side custom elements.
- Leverage on custom elements instead of building a framework to manage the virtual dom.

## TODO

- [x] Parse html.
- [x] Render html server side.
- [x] Parse custom elements.
- [x] Render custom elements server side.
- [ ] Hydrate custom elements client side.
